---
title: "Compare methods"
author: "Sean Rohan"
date: "3/21/2022"
output: html_document
---

```{r setup}
library(gapctd)
library(ggplot2)

# Select vessel, year, and region
vessel <- 162
year <- 2021
region <- "BS"
ctd_dir <- "G:/RACE_CTD/data/2021/ebs/v162"

# Establish Oracle connection connection
channel <- gapctd::get_connected(schema = "AFSC")

```

```{r v0}
run_method(vessel = vessel,
           year = year,
           region = region,
           ctd_dir = ctd_dir,
           channel = channel,
           processing_method = "sbe19plus",
           rm_files = "y")
```

# Align temperature shift = +0.25 s

```{r v1}
run_method(vessel = vessel,
           year = year,
           region = region,
           ctd_dir = ctd_dir,
           channel = channel,
           processing_method = "sbe19plus_v1",
           rm_files = "y")
```

# Align temperature shift = +0.50 s

```{r v2}
run_method(vessel = vessel,
           year = year,
           region = region,
           ctd_dir = ctd_dir,
           channel = channel,
           processing_method = "sbe19plus_v2",
           rm_files = "y")
```

# Align temperature shift = +0.75 s

```{r v3}
run_method(vessel = vessel,
           year = year,
           region = region,
           ctd_dir = ctd_dir,
           channel = channel,
           processing_method = "sbe19plus_v3",
           rm_files = "y")
```

# Align temperature shift = +1.00 s

```{r v4}
gapctd::run_method(vessel = vessel,
                   year = year,
                   region = region,
                   ctd_dir = ctd_dir,
                   channel = channel,
                   processing_method = "sbe19plus_v4",
                   rm_files = "y")
```

# Align temperature shift = +0.625 s

```{r v5}
gapctd::run_method(vessel = vessel,
                   year = year,
                   region = region,
                   ctd_dir = ctd_dir,
                   channel = channel,
                   processing_method = "sbe19plus_v5",
                   rm_files = "y")
```

# Compare methods and make plots

```{r}

dat <- gapctd::compare_methods(prefix = "align_ctd_method", 
                                           method_labels = c("No align", "Temperature +0.25 s", "Temperature +0.50 s", "Temperature +0.625 s", "Temperature +0.75 s", "Temperature +1.00 s"),
                                           processing_method = c("sbe19plus", "sbe19plus_v1", "sbe19plus_v2", "sbe19plus_v5", "sbe19plus_v3", "sbe19plus_v4"),
                                           return_output = TRUE)
```