#' Calculate fixed depth temperature and salinity (SBEDP workflow)
#' 
#' Use the OCE package to retrieve CTD near-surface data from upcast or downcast cnv files and calculate mean temperature and salinity for a fixed depth. Run after calc_bottom_mean().
#' 
#' @param haul_metadata_path Character vector. Path to haul data .csv generated by get_bottom_data().
#' @param depth Numeric vector (1L or 2L) indicating a fixed depth or range of depths from which to calculate a mean.
#' @param append_haul_metadata Logical. Should the file named in haul_metadata_path be appended (overwritten) to include mean surface values and metadata?
#' @param cast_direction Character vector, either "upcast" or "downcast."
#' @export

calc_fixed_depth_ts <- function(haul_metadata_path = list.files(paste0(getwd(), "/metadata/"), full.names = TRUE),
                              depth_interval = 1,
                              cast_direction = "upcast",
                              append_haul_metadata = TRUE) {
  
  haul_metadata_path = list.files(paste0(getwd(), "/metadata/"), 
                                  full.names = TRUE)
  
  cd_short <- c("d", "d", "u", "u")[match(tolower(cast_direction), c("downcast", "d", "upcast", "u"))]
  
  if(length(haul_metadata_path) != 1) {
    stop(paste("get_haul_events(): Argument haul_meta_data path must only be file but has length ", length(haul_metadata_path)))
  }
  
  # Load haul metadata file
  haul_metadata <- read.csv(file = haul_metadata_path, 
                            stringsAsFactors = FALSE)
  
  out_df <- haul_metadata
  
  # Extract surface data from downcasts
  for(i in 1:nrow(haul_metadata)) {
    
    if(i%%50 == 0) {
      print(paste0("Calculating surface values from file ", i, " out of ", nrow(haul_metadata)))
    }
    
    fpath <- list.files(here::here("final_cnv"), pattern = sub("\\_raw.*", "", haul_metadata$cnv_file_name[i]), 
                        full.names = TRUE)
    fpath <- fpath[grepl(pattern = paste0(cd_short, sub("\\_raw.*", "", haul_metadata$cnv_file_name[i])), fpath, fixed = TRUE)]
    
    if(length(fpath) == 1) {
      
      cast_dat <- suppressWarnings(oce::read.ctd.sbe(file = fpath))
      
      temp_vec <- cast_dat@data$temperature[cast_dat@data$depth >= min(depth_interval) & cast_dat@data$depth <= max(depth_interval)]
      sa_vec <- cast_dat@data$gsw_saA0[cast_dat@data$depth >= min(depth_interval) & cast_dat@data$depth <= max(depth_interval)]
      sp_vev <- cast_dat@data$salinity[cast_dat@data$depth >= min(depth_interval) & cast_dat@data$depth <= max(depth_interval)]
      
      out_df$CTD_MEAN_TEMPERATURE[i] <- mean(temp_vec, na.rm = TRUE)
      out_df$CTD_MEAN_SALINITY_SA[i] <- mean(sa_vec, na.rm = TRUE)
      out_df$CTD_MEAN_SALINITY_SP[i] <- mean(sp_vev, na.rm = TRUE)
      
    }
    
  }
  
  names(out_df)[names(out_df) == "CTD_MEAN_TEMPERATURE"] <- paste0("CTD_MEAN_TEMPERATURE_", toupper(cast_direction), "_", paste(depth_interval, collapse = "_"))
  names(out_df)[names(out_df) == "CTD_MEAN_SALINITY_SA"] <- paste0("CTD_MEAN_SALINITY_SA_", toupper(cast_direction), "_", paste(depth_interval, collapse = "_"))
  names(out_df)[names(out_df) == "CTD_MEAN_SALINITY_SP"] <- paste0("CTD_MEAN_SALINITY_SP_", toupper(cast_direction), "_", paste(depth_interval, collapse = "_"))
  
  if(append_haul_metadata) {
    write.csv(x = out_df, 
              file = haul_metadata_path, 
              row.names = FALSE)
  }
  
  return(out_df)
  
}