#' Calculate station surface temperature and salinity
#' 
#' Use the OCE package to retrieve CTD near-surface data from downcast cnv files and calculate mean surface temperature and salinity. Run after calc_bottom_mean().
#' 
#' @param haul_metadata_path Character vector. Path to haul data .csv generated by get_bottom_data().
#' @param depth_inteval Range of depths to use to calculate means.
#' @param append_haul_metadata Logical. Should the file named in haul_metadata_path be appended (overwritten) to include mean surface values and metadata?
#' @export

calc_surface_mean <- function(haul_metadata_path = list.files(paste0(getwd(), "/metadata/"), full.names = TRUE),
                              depth_interval = c(2,5),
                              append_haul_metadata = TRUE) {
  if(length(haul_metadata_path) != 1) {
    stop(paste("get_haul_events(): Argument haul_meta_data path must only be file but has length ", length(haul_metadata_path)))
  }
  
  # Load haul metadata file
  haul_metadata <- read.csv(file = haul_metadata_path, 
                            stringsAsFactors = FALSE)
  
  out_df <- haul_metadata
  
  # Extract surface data from downcasts
  for(i in 1:nrow(haul_metadata)) {
    
    if(i%%50 == 0) {
      print(paste0("Calculating surface values from file ", i, " out of ", nrow(haul_metadata)))
    }
    
    fpath <- list.files(here::here("final_cnv"), pattern = sub("\\_raw.*", "", haul_metadata$cnv_file_name[i]), 
                        full.names = TRUE)
    fpath <- fpath[grepl(pattern = paste0("u", sub("\\_raw.*", "", haul_metadata$cnv_file_name[i])), fpath, fixed = TRUE)]
    
    if(length(fpath) == 1) {
      
      cast_dat <- suppressWarnings(oce::read.ctd.sbe(file = fpath))
      
      out_df$CTD_MEAN_SURFACE_TEMPERATURE_C[i] <- mean(cast_dat@data$temperature[cast_dat@data$depth >= depth_interval[1] & cast_dat@data$depth <= depth_interval[2]], na.rm = TRUE)
      out_df$CTD_MEAN_SURFACE_SALINITY_SA[i] <- mean(cast_dat@data$gsw_saA0[cast_dat@data$depth >= depth_interval[1] & cast_dat@data$depth <= depth_interval[2]], na.rm = TRUE)
      out_df$CTD_MEAN_SURFACE_SALINITY_SP[i] <- mean(cast_dat@data$salinity[cast_dat@data$depth >= depth_interval[1] & cast_dat@data$depth <= depth_interval[2]], na.rm = TRUE)
    }
    
  }
  
  if(append_haul_metadata) {
    write.csv(x = out_df, 
              file = haul_metadata_path, 
              row.names = FALSE)
  }
  
  return(out_df)
  
}