#' Make sections from upcasts and downcasts
#' 
#' Split cnv file data into upcast and downcast files based on haul event times using the SBEDataProcessing 'section' module. This is used because SBEDataProcessing split methods result in profiles that include samples while the trawl was being towed along the bottom, which results in sampling artifacts in the bottom depth bin.
#' 
#' @param haul_metadata_path Character vector. Path to haul data .csv generated by get_bottom_data().
#' @param pattern Character vector. Suffix of cnv file to search for. Default = "TEOS10.cnv"
#' @param xmlcon_file xmlcon file
#' @param section_bat section batch file
#' @param pressure_bat pressure batch file
#' @param binavg_bat binavg batch file
#' @export

make_cast_sections <- function(haul_metadata_path = list.files(paste0(getwd(), "/metadata/"), full.names = TRUE),
                               pattern = "TEOS10.cnv", 
                               xmlcon_file = NA,
                               section_bat = NA,
                               pressure_bat = NA,
                               binavg_bat = NA) {
  
  haul_metadata <- read.csv(file = haul_metadata_path, 
                            stringsAsFactors = FALSE)
  append_char <- c("_downcast", "_upcast")
  
  # Setup xmlcon file
  if(is.na(xmlcon_file)) {
    print("Automatically retrieving .xmlcon (no user-specified argument to xmlcon_file)")
    xmlcon_file <- list.files("./psa_xmlcon/", pattern = ".xmlcon")
    
    if(length(xmlcon_file) < 1) {
      stop(paste0("No .xmlcon file found in ", getwd(), "/psa_xmlcon/. Must have a valid .xmlcon file."))
    } 
  } else {
    if(!file.exists(paste0(getwd(), "/psa_xmlcon/", xmlcon_file))) {
      stop(paste0(xmlcon_file, " file not found in ", getwd(), "/psa_xmlcon/", ". Must have a valid .xmlcon file in /psa_xmlcon/."))
    }
  }
  
  # Setup batch files
  if(is.na(section_bat)) {
    print("Automatically selecting section.bat file (no user-specified argument to section_bat)")
    section_bat <- list.files(pattern = "section.bat")
    
    if(length(xmlcon_file) < 1) {
      stop(paste0("No .bat file found in ", getwd(), ". Must have a valid .bat file."))
    } 
  } else {
    if(!file.exists(paste0(getwd(), "/", section_bat))) {
      stop(paste0(section_bat, " file not found in ", getwd(), ". Must have a valid .bat file."))
    }
  }
  
  if(is.na(pressure_bat)) {
    print("Automatically selecting pressure.bat file (no user-specified argument to pressure_bat)")
    pressure_bat <- list.files(pattern = "pressure.bat")
    
    if(length(xmlcon_file) < 1) {
      stop(paste0("No .bat file found in ", getwd(), ". Must have a valid .bat file."))
    } 
  } else {
    if(!file.exists(paste0(getwd(), "/", pressure_bat))) {
      stop(paste0(pressure_bat, " file not found in ", getwd(), ". Must have a valid .bat file."))
    }
  }
  
  if(is.na(binavg_bat)) {
    print("Automatically selecting binavg.bat file (no user-specified argument to binavg_bat)")
    binavg_bat <- list.files(pattern = "bin.bat")
    
    if(length(xmlcon_file) < 1) {
      stop(paste0("No .bat file found in ", getwd(), ". Must have a valid .bat file."))
    } 
  } else {
    if(!file.exists(paste0(getwd(), "/", bin_bat))) {
      stop(paste0(binavg_bat, " file not found in ", getwd(), ". Must have a valid .bat file."))
    }
  }
  
  cnv_files <- list.files(here::here("cnv"), pattern = pattern, 
                          full.names = TRUE)
  
  deploy_id <- sub("\\_raw.*", "", list.files(here::here("cnv"), pattern = pattern))
  
  for(ii in 1:length(cnv_files)) {
    
    if(ii%%50 == 0) {
      message(paste0("Splitting upcast and downcast from file ", ii, " out of ", length(cnv_files)))
    }
    
    for(jj in 1:2) {
      
      oce_dat <- try(oce::read.ctd(cnv_files[ii]))
      
      ind_vec <- switch(jj,
                        `1` = { c(0, max(which(oce_dat@data$timeS < (haul_metadata$DOWNCAST_END_SECONDS[which(deploy_id[ii] == sub("\\_raw.*", "", haul_metadata$cnv_file_name))] + 30))))}, 
                        `2` = {c(min(which(oce_dat@data$timeS > (haul_metadata$UPCAST_START_SECONDS[which(deploy_id[ii] == sub("\\_raw.*", "", haul_metadata$cnv_file_name))] - 30))), 100000)})
      
      section_path <- here::here("psa_xmlcon", "Section.psa")
      section_psa_file <- readLines(section_path)
      
      append_index <- which(grepl(pattern = "  <NameAppend", section_psa_file))
      min_val_index <- which(grepl(pattern = "<MinValue", section_psa_file))
      max_val_index <- which(grepl(pattern = "<MaxValue", section_psa_file))
      
      
      
      if(!any(is.na(ind_vec))) {
        section_psa_file[append_index] <- paste0("  <NameAppend value=\"_", append_char[jj],  "\" />")
        section_psa_file[min_val_index] <- paste0("  <MinValue value=\"",ind_vec[1], ".000000","\" />")
        section_psa_file[max_val_index] <- paste0("  <MaxValue value=\"",ind_vec[2], ".000000","\" />")
        
        psa_con <- file(section_path)
        writeLines(text = section_psa_file, con = psa_con)
        
        close(psa_con)
        
        # Run section function
        cmd <- paste0("sbebatch ", getwd(), "/", section_bat, " ",  
                      getwd(), " ", #%1
                      xmlcon_file, " ", #%2
                      cnv_files[ii], " ", #%3
                      section_path, " ", #%4
                      append_char[jj], " #m") #%5
        system(cmd)
      }
    }
  }
  
  # Remove surface values (pressure < 0.5) from cnv downcast files
  pressure_path <- here::here("psa_xmlcon", "Section_Pressure.psa")
  pressure_psa_file <- readLines(pressure_path)
  
  pressure_index <- which(grepl(pattern = "  <PressureCast ", pressure_psa_file))
  pressure_psa_file[pressure_index] <- "  <PressureCast value=\"0\" high=\"1\" low=\"0\" initialValue=\"0\" />" 
  psa_con <- file(pressure_path)
  writeLines(text = pressure_psa_file, con = psa_con)
  close(psa_con)
  
  system(paste0("sbebatch ", getwd(), "/", pressure_bat, " ", 
                getwd(), " ", #%1
                xmlcon_file, " ", #%2
                pressure_path, " ",
                paste0(append_char[1],".cnv"))) #%3
  
  # Remove surface values (pressure < 0.5) from cnv upcast files 
  pressure_psa_file <- readLines(pressure_path)
  
  pressure_index <- which(grepl(pattern = "  <PressureCast ", pressure_psa_file))
  pressure_psa_file[pressure_index] <- "  <PressureCast value=\"1\" high=\"1\" low=\"0\" initialValue=\"0\" />" 
  
  psa_con <- file(pressure_path)
  writeLines(text = pressure_psa_file, con = psa_con)
  close(psa_con)
  
  system(paste0("sbebatch ", getwd(), "/", pressure_bat, " ", 
                getwd(), " ", #%1
                xmlcon_file, " ", #%2
                pressure_path, " ",  #%3
                paste0(append_char[2],".cnv") #%4
                ))
  
  # Remove downcast files from upcast alignments and upcast files from downcast alignments
  print("Binning upcast and downcast data")
  system(command = paste0("sbebatch ", getwd(), "/", binavg_bat, " ", getwd(), " ", xmlcon_file))
  
  upcast_files <- list.files(path = here::here("cnv"), pattern = "_uuu_", full.names = TRUE)
  file.remove(upcast_files[grep(pattern = "downcast", x = upcast_files)])
  
  downcast_files <- list.files(path = here::here("cnv"), pattern = "_ddd_", full.names = TRUE)
  file.remove(downcast_files[grep(pattern = "upcast", x = downcast_files)])
  
}