#' Filter out bad bottom and surface data and cnvs
#' 
#' Filter out data bottom and surface averages that show evidence of operational error and equipment failure (e.g. CTD on while on deck, not reaching haul depth). Run after calc_surface_mean().
#' 
#' @param haul_metadata_path Character vector. Path to haul data .csv generated by get_bottom_data().
#' @param max_diff_bt_ctd_depth Numeric vector (1L). Maximum permissable difference between BT and CTD depth. Default = 10 m.
#' @param min_ctd_depth Numeric vector (1L). Minimum haul depth in meters. Default = 5 m.
#' @param vessel Required. Vessel number as a numeric vector.
#' @param year Required. Year as a numeric vector. 
#' @param region Required. Region as a character vector. Either "BS", "AI", or "GOA".
#' @export


remove_bad_station_data <- function(haul_metadata_path = list.files(paste0(getwd(), "/metadata/"), full.names = TRUE),
                                    max_diff_bt_ctd_depth = 10,
                                    min_ctd_depth = 5,
                                    region,
                                    vessel,
                                    year) {
  
  region <- toupper(region)
  
  if(length(haul_metadata_path) != 1) {
    stop(paste("get_haul_events(): Argument haul_meta_data path must only be file but has length ", length(haul_metadata_path)))
  }
  
  # Load haul metadata file
  haul_dat <- read.csv(file = haul_metadata_path, 
                       stringsAsFactors = FALSE)
  haul_dat$flag <- 0
  
  index_error <- unique(c(which(haul_dat$CTD_MEAN_HAUL_DEPTH < 5), 
                          which(abs(haul_dat$BT_GEAR_DEPTH - haul_dat$CTD_MEAN_HAUL_DEPTH) > 7), 
                          which(is.na(haul_dat$CTD_MEAN_HAUL_DEPTH))))
  haul_dat$flag[index_error] <- -1
  
  bad_files <- sub("\\_raw.*", "", haul_dat$cnv_file_name[index_error])
  
  # Move bad cnv files
  for(i in 1:length(bad_files)) {
    f_list <- list.files(pattern = bad_files[i], recursive = TRUE, full.names = TRUE)
    f_list <- f_list[grepl(pattern = ".cnv", x = f_list, fixed = TRUE)]
    f_newloc <- gsub(pattern = "/cnv/", replacement = "/bad_cnv/", f_list)
    file.rename(from = f_list, 
                to = f_newloc)
  }
  
  # Remove erroneous data from data frame
  haul_dat <- haul_dat[-index_error,]
  
  write.csv(haul_dat, 
            file = here::here("output", paste0("CTD_", region, "_", year, "_", vessel, ".csv")),
            row.names = FALSE)
  
  return(haul_dat)
  
}